resolver 127.0.0.11 valid=10s;

upstream cells {
    hash $arg_user_id consistent;
    server cell-1-api:8000;
    server cell-2-api:8000;
}

server {
    listen 80;
    
    location / {
        proxy_pass http://cells;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location /stats {
        stub_status on;
    }
}