apiVersion: apps/v1
kind: Deployment
metadata:
  name: cell-2-worker
  namespace: cell-2
  labels:
    app: cell-2-worker
    cell: cell-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cell-2-worker
  template:
    metadata:
      labels:
        app: cell-2-worker
        cell: cell-2
    spec:
      containers:
        - name: worker
          image: cell-based-architecture-worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CELL_ID
              value: "cell-2"
            - name: RABBITMQ_HOST
              value: "cell-2-rabbitmq"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
