upstream cells {
    hash $arg_user_id consistent;
    server cell-poc-cell-1-api-1:8000;
    server cell-poc-cell-2-api-1:8000;
}

server {
    listen 80;
    
    location / {
        proxy_pass http://cells;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location /stats {
        stub_status on;
    }
}